name: endec
description: A format-agnostic serialization framework inspired by serde and DataFixerUpper
repository: https://github.com/gliscowo/endec.dart
version: 0.1.0

environment:
  sdk: ^3.1.3

dependencies:
  meta: ^1.12.0

dev_dependencies:
  lints: ^4.0.0
