name: endec_nbt
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  collection: ^1.18.0
  endec:
    path: ..

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0