name: endec_nbt
description: An implementation of Minecraft's Named Binary Tag format for endec
version: 0.1.0
repository: https://github.com/gliscowo/endec.dart

publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  endec:
    path: ..
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
