builders:
  endecBuilder:
    import: "package:endec_builder/endec_builder.dart"
    builder_factories: ["endecBuilder"]
    build_extensions: {".dart": [".endec.g.part"]}
    build_to: cache
    auto_apply: dependents
    applies_builders: ["source_gen|combining_builder"]