name: endec_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  endec:
    path: ..
  meta: ^1.15.0
  source_gen: ^1.5.0
  source_helper: ^1.3.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
