name: endec_builder
description: A build system builder for automatically generating struct endecs
version: 0.1.0
repository: https://github.com/gliscowo/endec.dart

publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  endec:
    path: ..
  analyzer: ^6.4.1
  build: ^2.4.1
  meta: ^1.15.0
  source_gen: ^1.5.0
  source_helper: ^1.3.4

dev_dependencies:
  lints: ^4.0.0
