name: endec_edm
description: Wrapper types for the endec data model and serialization support
version: 0.1.0
repository: https://github.com/gliscowo/endec.dart

resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  endec: ^0.1.0
  collection: ^1.19.0
  meta: ^1.12.0

dev_dependencies:
  lints: ^4.0.0
