name: endec_edm
description: Wrapper types for the endec data model and serialization support
version: 0.1.0
repository: https://github.com/gliscowo/endec.dart

publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  endec:
    path: ..
  meta: ^1.12.0

dev_dependencies:
  lints: ^4.0.0
