name: endec_edm
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  endec:
    path: ..
  meta: ^1.12.0

dev_dependencies:
  lints: ^4.0.0
